package com.budget.application;

import com.budget.domain.CategoryRule;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

final class BudgetCatalog {
    static final Set<String> INCOME_CATEGORIES = Set.of("Pensja Aleksander", "Pensja Volvo");
    static final Set<String> EXCLUDED = Set.of(
            "Przelewy własne", "Oszczędności i inwestycje", "Spłata karty kredytowej",
            "Wpłata gotówki", "Zwroty i korekty", "Odsetki", "Zwrot podatku",
            "Nadpłata kredytu", "Gotówka do rozliczenia"
    );
    static final Set<String> DISCRETIONARY = Set.of(
            "Jedzenie poza domem", "Odzież i obuwie", "Wyjścia i wydarzenia",
            "Podróże i wyjazdy", "Multimedia, książki i prasa", "Sport i hobby",
            "Prezenty i wsparcie", "Elektronika", "Zakupy w podróży", "Inne osobiste"
    );

    static final Map<String, String> GROUPS = Map.ofEntries(
            Map.entry("Żywność i chemia", "Potrzeby podstawowe"),
            Map.entry("Jedzenie poza domem", "Styl życia"),
            Map.entry("Zdrowie i uroda", "Potrzeby podstawowe"),
            Map.entry("Odzież i obuwie", "Styl życia"),
            Map.entry("Wyjścia i wydarzenia", "Styl życia"),
            Map.entry("TV, internet, telefon", "Rachunki"),
            Map.entry("Zwierzęta", "Potrzeby podstawowe"),
            Map.entry("Podróże i wyjazdy", "Styl życia"),
            Map.entry("Zakupy w podróży", "Styl życia"),
            Map.entry("Transport i parking", "Transport"),
            Map.entry("Multimedia, książki i prasa", "Styl życia"),
            Map.entry("Dom i wyposażenie", "Dom"),
            Map.entry("Sport i hobby", "Styl życia"),
            Map.entry("Prezenty i wsparcie", "Styl życia"),
            Map.entry("Prąd", "Rachunki"),
            Map.entry("Podatki", "Podatki"),
            Map.entry("Czynsz i wynajem", "Mieszkanie"),
            Map.entry("Remont i ogród", "Dom"),
            Map.entry("Elektronika", "Styl życia"),
            Map.entry("Ubezpieczenia", "Rachunki"),
            Map.entry("Lekarz i apteka", "Zdrowie"),
            Map.entry("Paliwo i auto", "Transport"),
            Map.entry("Opłaty bankowe i odsetki", "Finanse"),
            Map.entry("Wypłata gotówki", "Gotówka"),
            Map.entry("Spłaty i raty", "Finanse"),
            Map.entry("Rata kredytu", "Finanse"),
            Map.entry("Nadpłata kredytu", "Finanse"),
            Map.entry("Spłata karty kredytowej", "Finanse"),
            Map.entry("Oszczędności i inwestycje", "Oszczędności"),
            Map.entry("Przelewy własne", "Transfery"),
            Map.entry("Wpływy", "Wpływy"),
            Map.entry("Pensja Aleksander", "Wpływy"),
            Map.entry("Pensja Volvo", "Wpływy"),
            Map.entry("Zwroty i korekty", "Transfery"),
            Map.entry("Odsetki", "Transfery"),
            Map.entry("Zwrot podatku", "Transfery"),
            Map.entry("Inne osobiste", "Styl życia"),
            Map.entry("Do sprawdzenia", "Do sprawdzenia"),
            Map.entry("Marketplace i zakupy online", "Styl życia"),
            Map.entry("Opłaty publiczne", "Opłaty"),
            Map.entry("Opłaty bankowe", "Finanse"),
            Map.entry("Wpłata gotówki", "Gotówka"),
            Map.entry("Gotówka do rozliczenia", "Gotówka")
    );

    static final Map<String, String> BUDGET_AREAS = Map.ofEntries(
            Map.entry("Pensja Aleksander", "Przychody"),
            Map.entry("Pensja Volvo", "Przychody"),
            Map.entry("Wpływy", "Przychody"),
            Map.entry("Żywność i chemia", "Koszty codzienne"),
            Map.entry("Jedzenie poza domem", "Styl życia"),
            Map.entry("Zdrowie i uroda", "Koszty codzienne"),
            Map.entry("Lekarz i apteka", "Koszty codzienne"),
            Map.entry("Odzież i obuwie", "Styl życia"),
            Map.entry("Wyjścia i wydarzenia", "Styl życia"),
            Map.entry("TV, internet, telefon", "Koszty stałe"),
            Map.entry("Zwierzęta", "Koszty codzienne"),
            Map.entry("Podróże i wyjazdy", "Styl życia"),
            Map.entry("Zakupy w podróży", "Styl życia"),
            Map.entry("Transport i parking", "Transport"),
            Map.entry("Paliwo i auto", "Transport"),
            Map.entry("Multimedia, książki i prasa", "Styl życia"),
            Map.entry("Dom i wyposażenie", "Dom i mieszkanie"),
            Map.entry("Remont i ogród", "Dom i mieszkanie"),
            Map.entry("Czynsz i wynajem", "Dom i mieszkanie"),
            Map.entry("Prąd", "Koszty stałe"),
            Map.entry("Ubezpieczenia", "Koszty stałe"),
            Map.entry("Podatki", "Koszty stałe"),
            Map.entry("Opłaty publiczne", "Koszty stałe"),
            Map.entry("Sport i hobby", "Styl życia"),
            Map.entry("Prezenty i wsparcie", "Styl życia"),
            Map.entry("Elektronika", "Styl życia"),
            Map.entry("Marketplace i zakupy online", "Zakupy mieszane"),
            Map.entry("Inne osobiste", "Styl życia"),
            Map.entry("Rata kredytu", "Zobowiązania"),
            Map.entry("Spłaty i raty", "Zobowiązania"),
            Map.entry("Opłaty bankowe i odsetki", "Zobowiązania"),
            Map.entry("Opłaty bankowe", "Zobowiązania"),
            Map.entry("Oszczędności i inwestycje", "Majątek i inwestycje"),
            Map.entry("Nadpłata kredytu", "Majątek i inwestycje"),
            Map.entry("Przelewy własne", "Transfery techniczne"),
            Map.entry("Spłata karty kredytowej", "Transfery techniczne"),
            Map.entry("Zwroty i korekty", "Transfery techniczne"),
            Map.entry("Odsetki", "Transfery techniczne"),
            Map.entry("Zwrot podatku", "Transfery techniczne"),
            Map.entry("Wypłata gotówki", "Transfery techniczne"),
            Map.entry("Wpłata gotówki", "Transfery techniczne"),
            Map.entry("Gotówka do rozliczenia", "Transfery techniczne"),
            Map.entry("Do sprawdzenia", "Do sprawdzenia")
    );

    static final Map<String, String> BUDGET_BUCKETS = Map.ofEntries(
            Map.entry("Pensja Aleksander", "Przychody"),
            Map.entry("Pensja Volvo", "Przychody"),
            Map.entry("Wpływy", "Przychody"),
            Map.entry("Żywność i chemia", "Potrzeby"),
            Map.entry("Zdrowie i uroda", "Potrzeby"),
            Map.entry("Lekarz i apteka", "Potrzeby"),
            Map.entry("Zwierzęta", "Potrzeby"),
            Map.entry("Czynsz i wynajem", "Potrzeby"),
            Map.entry("Prąd", "Potrzeby"),
            Map.entry("TV, internet, telefon", "Potrzeby"),
            Map.entry("Ubezpieczenia", "Potrzeby"),
            Map.entry("Podatki", "Potrzeby"),
            Map.entry("Opłaty publiczne", "Potrzeby"),
            Map.entry("Transport i parking", "Potrzeby"),
            Map.entry("Paliwo i auto", "Potrzeby"),
            Map.entry("Rata kredytu", "Potrzeby"),
            Map.entry("Spłaty i raty", "Potrzeby"),
            Map.entry("Opłaty bankowe", "Potrzeby"),
            Map.entry("Opłaty bankowe i odsetki", "Potrzeby"),
            Map.entry("Dom i wyposażenie", "Potrzeby mieszane"),
            Map.entry("Remont i ogród", "Potrzeby mieszane"),
            Map.entry("Jedzenie poza domem", "Zachcianki"),
            Map.entry("Odzież i obuwie", "Zachcianki"),
            Map.entry("Wyjścia i wydarzenia", "Zachcianki"),
            Map.entry("Podróże i wyjazdy", "Zachcianki"),
            Map.entry("Zakupy w podróży", "Zachcianki"),
            Map.entry("Multimedia, książki i prasa", "Zachcianki"),
            Map.entry("Sport i hobby", "Zachcianki"),
            Map.entry("Prezenty i wsparcie", "Zachcianki"),
            Map.entry("Elektronika", "Zachcianki"),
            Map.entry("Marketplace i zakupy online", "Zachcianki do rozbicia"),
            Map.entry("Inne osobiste", "Zachcianki"),
            Map.entry("Oszczędności i inwestycje", "Oszczędzanie/inwestycje"),
            Map.entry("Nadpłata kredytu", "Oszczędzanie/inwestycje"),
            Map.entry("Przelewy własne", "Transfer techniczny"),
            Map.entry("Spłata karty kredytowej", "Transfer techniczny"),
            Map.entry("Zwroty i korekty", "Transfer techniczny"),
            Map.entry("Odsetki", "Transfer techniczny"),
            Map.entry("Zwrot podatku", "Transfer techniczny"),
            Map.entry("Wypłata gotówki", "Transfer techniczny"),
            Map.entry("Wpłata gotówki", "Transfer techniczny"),
            Map.entry("Gotówka do rozliczenia", "Transfer techniczny"),
            Map.entry("Do sprawdzenia", "Do sprawdzenia")
    );

    static final Map<String, String> FIXEDNESS = Map.ofEntries(
            Map.entry("Czynsz i wynajem", "Stałe"),
            Map.entry("Rata kredytu", "Stałe"),
            Map.entry("Prąd", "Stałe"),
            Map.entry("TV, internet, telefon", "Stałe"),
            Map.entry("Ubezpieczenia", "Stałe"),
            Map.entry("Podatki", "Stałe"),
            Map.entry("Opłaty publiczne", "Stałe"),
            Map.entry("Spłaty i raty", "Stałe"),
            Map.entry("Opłaty bankowe", "Stałe"),
            Map.entry("Opłaty bankowe i odsetki", "Stałe"),
            Map.entry("Żywność i chemia", "Zmienne konieczne"),
            Map.entry("Zdrowie i uroda", "Zmienne konieczne"),
            Map.entry("Lekarz i apteka", "Zmienne konieczne"),
            Map.entry("Zwierzęta", "Zmienne konieczne"),
            Map.entry("Transport i parking", "Zmienne konieczne"),
            Map.entry("Paliwo i auto", "Zmienne konieczne"),
            Map.entry("Oszczędności i inwestycje", "Oszczędności"),
            Map.entry("Nadpłata kredytu", "Oszczędności")
    );

    static final List<CategoryRule> RULES = List.of(
            rule("RĘCZNA SPŁATA KARTY KREDYT|RECZNA SPLATA KARTY KREDYT|SPŁATA KARTY|SPLATA KARTY|SPŁATA - PRZELEW WEWNĘTRZNY|SPLATA - PRZELEW WEWNETRZNY", "Spłata karty kredytowej"),
            rule("KREDYT - (WCZEŚNIEJSZA SPŁATA|WCZESNIEJSZA SPLATA)", "Nadpłata kredytu"),
            rule("KREDYT - (SPŁATA RATY|SPLATA RATY)", "Rata kredytu"),
            rule("ONLINE\\.SANTANDERC|ONLINE\\.SANTANDERCONSUMER|SANTANDERCONSUMER", "Spłaty i raty"),
            rule("\\bRATA\\b|\\bRATY\\b|POŻYCZKA|POZYCZKA", "Spłaty i raty"),
            rule("PRZELEW WŁASNY|PRZELEW WLASNY|PRZELEW ŚRODKÓW|PRZELEW SRODKOW|PRZELEW WEWNĘTRZNY|PRZELEW WEWNETRZNY", "Przelewy własne"),
            rule("ALEKSANDER KARPOWICZ SOFTWARE.*PRZELEW ZEWNĘTRZNY WYCHODZĄCY", "Przelewy własne"),
            rule("ALEKSANDER KARPOWICZ SOFTWARE.*(WYNAGRODZENIE|PRZELEW EXPRESS ELIXIR PRZYCH)|PRZELEW EXPRESS ELIXIR PRZYCH\\..*ALEKSANDER KARPOWICZ SOFTWARE", "Pensja Aleksander"),
            rule("VOLVO POLSKA.*(WYNAGRODZENIE|SALARY)", "Pensja Volvo"),
            rule("ZWROT ZAKUPU|DOF DO OKULAROW|ADYEN|TOTALIZATOR SPORTOWY", "Zwroty i korekty"),
            rule("KAPITALIZACJA ODSETEK", "Odsetki"),
            rule("ZWROT Z PODATKU|URZĄD SKARBOWY|URZAD SKARBOWY", "Zwrot podatku"),
            rule("PRZELEW DO BM MBANKU|IKZE|ZAKUP SFI|FUNDUSZ|SUBFUNDUSZ|MAKLERSK|BROKERAGE", "Oszczędności i inwestycje"),
            rule("WYPŁATA GOTÓWKI|WYPLATA GOTOWKI|BANKOMAT|ATM", "Gotówka do rozliczenia"),
            rule("WPŁATA WE WPŁATOMACIE|WPLATA WE WPLATOMACIE", "Wpłata gotówki"),
            rule("DOMOWSKIEGO 19F|DMOWSKIEGO 19F|OPLATY, ZALICZKA|OPŁATY, ZALICZKA|CZYNSZ|WYNAJEM", "Czynsz i wynajem"),
            rule("TAURON|PGE|ENERGA|ENEA|PRĄD|PRAD|GAZ", "Prąd"),
            rule("KORBANK|PLUS TATIANA|PLUS ALEKSANDER|WWW\\.PLUS\\.PL|SSL\\.PLUSGSM\\.PL|ORANGE|T-MOBILE|UPC|VECTRA|NETIA|\\bPLAY\\b.*(TELEFON|ABONAMENT|DOŁADOWANIE|DOLADOWANIE)", "TV, internet, telefon"),
            rule("PROWIZJA OD WYPŁATY GOTÓWKI|PROWIZJA OD WYPLATY GOTOWKI|PRZELEW EXPRESS ELIXIR WYCH|MTRANSFER BLUE MEDIA", "Opłaty bankowe"),
            rule("PLIP\\.WROCLAW\\.PL|PLIP\\.UM\\.WROC\\.PL|GMINA WROCŁAW|GMINA WROCLAW", "Opłaty publiczne"),
            rule("SKŁADKA UB|SKLADKA UB|UBEZPIECZ|POLISA|PZU|UNIQA|WARTA|LINK4|ALLIANZ|GENERALI|VWFS UBEZPIECZENIA", "Ubezpieczenia"),
            rule("PODATEK|URZAD SKARBOWY|URZĄD SKARBOWY|ZUS", "Podatki"),
            rule("BIEDRONKA|LIDL|CARREFOUR|AUCHAN|KAUFLAND|ALDI|ZABKA|ŻABKA|DINO|STOKROTKA|LEWIATAN|SPOLEM|SPOŁEM|DELIKATESY|SKLEP BLUMIS", "Żywność i chemia"),
            rule("BILLA|TIGER|CARREF GIRONA|GROCERY|SUPERMARKET|MARKET|TESCO|PIEKARNIA|CUKIERNIA|SASIEDZI|PURI|SPAR|DELIKOMAT|GORĄCO POLECAM|GORACO POLECAM|KUCHNIE SWIATA|CZAS NA HERBAT|SUPERMERCAT|COALIMENT|CELLER PALOU|SKLEP 800|REKREATYWA|FAMILIJNA|SLODKI CHLOPAK|SŁODKI CHŁOPAK|EL MERCADET", "Żywność i chemia"),
            rule("ROSSMANN|HEBE|SEPHORA|DOUGLAS|APTEKA|APOTHEKE|DOZ|SUPER-PHARM|LEKARZ|MEDICOVER|LUX MED|LUXMED|DENT|FARMAC|FIELMANN|M-DENT|ALAB|MEDICCENTRE|ZBADAJKLESZCZA|NOTINO|OPTYCZNY|VITA RECEPCJA|WITEK|DM-DROGERIE|FRISER|OVO MEDICAL|ZETMED|MIDNIGHT MEADO", "Zdrowie i uroda"),
            rule("RESTAUR|RESTAURACJA|CAFE|KAWA|KIOSSO|PIZZA|SUSHI|BURGER|BURGUER|MCDONALD|KFC|POPEYES|PYSZNE|UBER EATS|BOLT FOOD|BAR |KUCHNIA|GLOVO|WOLT|LEPIONE|EXPRESS ORIENTAL|ATO RAMEN|GASTHOF|WIENERWIRTSCHAFT|PIEROGARNIA|PASIB|KIOSK PASIB|KIOSK PASI|MANGO MAMA|TUTTI SANTI|HALA SWIEBODZKI|HALA ŚWIEBODZKI|THAI EXPRESS|PAN PRECEL|SODEXO|STARBUCKS|SB NAMESTI SVOBODY|SBX WROCLAW|AMREST|BISTROCYKL|COSTA COFFEE|KEBAP|DONER|FOODIES|WAGOZERCY|EUREST|BB BRNO|BB VACLAVSKE|TENDUR|BELLA BEAN|KAVY|ORIGINAL KRUMLOV WAF|JEDZENIE|JEDZONKO|QUESA|KOREAŃCZYK|KOREANCZYK|CHINGU|CHATKA PRZY JATKACH|KARCZMA|CZARNA MAGIA|MAISTERSZTYK|LA FABIRCA|ENKLAWA|MANIA AL TAGLIO|SLIMAK", "Jedzenie poza domem"),
            rule("VINTED|ZALANDO|CCC|H&M|\\bHM\\b|RESERVED|SINSAY|MOHITO|ZARA|CROPP|OBUWIE|TK MAXX|DEICHMANN|PRIMARK|MEDICINE|WEARMEDICINE|HALF PRICE|TRACHTENMODE|SKLEP Z ODZIEZA|SP MEMERY|\\bHOUSE\\b|STRADIVARIUS|RESTYLE|TERRANOVA|LOKAAH|VENA SP|MARGO SP|DZIKIZACHOD|BALAGANSTUDIO|NEW YORKER|ROCKMETALSHOP", "Odzież i obuwie"),
            rule("KICKET|TICKET|TICKETMASTER|BILET|KINO|TEATR|EVENT|MUZEUM|KONCERT|BRUTALASSAULT|FLYN|NFCTRON|GOPAY|TIQETS|TIXYAPP|VIENNACONCERTS|EET RESIS FESTIVAL|SCHMITTENHOEHEBAHN|LANOVA DRAHA|BANYS ARABS|KISWE|OZZY|KUPBILECIK|STAGE24|CINEMA|GOOUT|PNGS|LOTTO|ENTRITT|NHM|CHRAM SV|SEDLEC|ZAMEK GRODZIEC|KNOCK OUT PRODUCTIONS|WPE W DZIEKANOWICACH", "Wyjścia i wydarzenia"),
            rule("NETFLIX|SPOTIFY|DISNEY|STEAM|EMPIK|GOOGLE PLAY|PLAYSTATION|ADOBE|KRD|ZECCER|FOTOJOKER|KSIEGRALNIA|KSIĘGRALNIA", "Multimedia, książki i prasa"),
            rule("E S CELRA|MOL |CS(?:P)?HM|SERWIS|CZĘŚCI|CZESCI|BOB|MOTORPOL|MYJNIA|ORLEN|BP |SHELL|CIRCLE K|STACJA", "Paliwo i auto"),
            rule("UBER|BOLT|FREE NOW|JAKDOJADE|ZTM|MPK|PKP|KOLEO|INTERCITY|FLIXBUS|INFOBUS|MPSA - A|WIENER LINIEN|PARKING|PARKOVISTE|PARKOMAT|APCOA|AUTOSTRADA|VIGNETTE|EDALNICE|DALNICKA|SYSTEMY POB|REZERWACJA\\.AIRPORT|PORT LOTNICZY|KARLSPLATZGARAGE|PARKUM|PARKPLATZ|GARAGE|GARAZE|PP BYSTRZYCA|KBU.*SSP|KBU.*SPP|GALERIA DOMINIKANSKA|AP RIERA SANT VICENC|AP EL GARRIGAL|AP SANTA CATERINA|PR CERNY MOST|DHL24|WOOD SP\\. Z O\\.O\\. WROCL", "Transport i parking"),
            rule("IKEA|CASTORAMA|LEROY|JYSK|AGATA|PEPCO|ACTION|OBI|BRICOMAN|ALL4HOM|ATASZEK|WOOLWORTH", "Dom i wyposażenie"),
            rule("KAKADU|ZOOPLUS|MAXI ZOO|WETERYNAR|VET|CENTRUM WETERYNARII|SKLEP ZOOLOGICZNY|MEDUZA|AQUAELZOO|ALE ANIMALE", "Zwierzęta"),
            rule("BOOKING|BKG\\*HOTEL|AIRBNB|HOTEL|PENSJONAT|BAJKOWA PRZYSTAŃ|RYANAIR|WIZZAIR|LOT\\.COM|LOT |TRAVEL|PODRÓŻ|SIXT|BOTIGA PUB FUND GALA DALI|SCHOENBRUNN|MS\\* THEHOUSE|ALPINCENTER|DOM ZU SALZBURG|VLTAVSKA POHADKA|PARK INN|ARCTIC CAMPERS|ARBIO", "Podróże i wyjazdy"),
            rule("AVOLTA|DUTY FREE|WT TG DF", "Zakupy w podróży"),
            rule("DECATHLON|THOMANN|KNOCKOUTMUSICSTORE|BLM\\*KOKONKI|KOKONKI|DACHSTEINSPORT|GIKME|MILITARIA.PL|ASSARION|FAJKOWO|ULTRA SUNN", "Sport i hobby"),
            rule("MEDIA EXPERT|MEDIA MARKT|ME M02|CYFROWE|RTV|AGD|ELECTRO|EURO\\.COM|KOMPUTRONIK|X-KOM|NEEWER", "Elektronika"),
            rule("ZEGAROWNIA|SUVENYRY|SOUVENIRS|EWIKING|KHM-KHM|BOLESLAWIEC|LOVE POLAND|DBFLORIST|PREZENT|FENIKS|MAGIC SILVER|JAPIER", "Prezenty i wsparcie"),
            rule("ALLEGRO|AMAZON|ALIEXPRESS|TEMU|PAYPAL \\*ETSY|ETSY|SELFIBOX|PAYPAL \\*", "Marketplace i zakupy online")
    );

    private BudgetCatalog() {
    }

    private static CategoryRule rule(String regex, String category) {
        return new CategoryRule(Pattern.compile(regex, Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE), category, regex);
    }
}
