CREATE TABLE budget_sinking_fund_categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_key VARCHAR(64)  NOT NULL REFERENCES budget_settings_profiles (settings_key) ON DELETE CASCADE,
    category     VARCHAR(160) NOT NULL,
    UNIQUE (settings_key, category)
);
