-- Phase 3c: classification rules become user-editable data. The regex/title matcher reads enabled
-- rules from this table (seeded from BudgetTaxonomy.RULES + private config on first boot, in declared
-- order as ascending priority; personal rules sit in a lower priority band so they still win).
-- pattern is wide enough for the long composite regexes (the dining-out rule is ~700 chars).
CREATE TABLE classification_rule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_type  VARCHAR(16)   NOT NULL DEFAULT 'title',
    pattern     VARCHAR(4000) NOT NULL,
    category_id VARCHAR(80)   NOT NULL REFERENCES category(category_id),
    priority    INTEGER       NOT NULL DEFAULT 1000,
    enabled     BOOLEAN       NOT NULL DEFAULT TRUE,
    source      VARCHAR(16)   NOT NULL DEFAULT 'user',
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_classification_rule_priority ON classification_rule (priority, id);
