CREATE TABLE reports (
    report_year INTEGER PRIMARY KEY,
    payload_json TEXT NOT NULL,
    input_csv VARCHAR(512),
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_count INTEGER NOT NULL,
    income DOUBLE PRECISION NOT NULL,
    spend DOUBLE PRECISION NOT NULL
);

CREATE TABLE import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER,
    input_csv VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE budget_transactions (
    report_year INTEGER NOT NULL,
    lp INTEGER NOT NULL,
    posted_date DATE NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    merchant VARCHAR(256),
    description TEXT,
    corrected_category VARCHAR(160),
    subcategory VARCHAR(160),
    amount DOUBLE PRECISION NOT NULL,
    analysis_spend DOUBLE PRECISION NOT NULL,
    payload_json TEXT NOT NULL,
    PRIMARY KEY (report_year, lp)
);
