DROP TABLE IF EXISTS report_large_oneoffs CASCADE;
DROP TABLE IF EXISTS report_recurring_merchants CASCADE;
DROP TABLE IF EXISTS report_merchant_summaries CASCADE;
DROP TABLE IF EXISTS report_fixedness_summaries CASCADE;
DROP TABLE IF EXISTS report_sinking_funds CASCADE;
DROP TABLE IF EXISTS report_month_alerts CASCADE;
DROP TABLE IF EXISTS report_month_category_status CASCADE;
DROP TABLE IF EXISTS report_month_control CASCADE;
DROP TABLE IF EXISTS report_category_limits CASCADE;
DROP TABLE IF EXISTS report_savings_plan CASCADE;
DROP TABLE IF EXISTS report_budget_mix CASCADE;
DROP TABLE IF EXISTS report_hierarchy_summaries CASCADE;
DROP TABLE IF EXISTS report_category_summaries CASCADE;
DROP TABLE IF EXISTS report_monthly_summaries CASCADE;
DROP TABLE IF EXISTS report_kpis CASCADE;
DROP TABLE IF EXISTS budget_transactions CASCADE;
DROP TABLE IF EXISTS import_runs CASCADE;
DROP TABLE IF EXISTS reports CASCADE;

CREATE TABLE reports (
    report_year INTEGER PRIMARY KEY,
    period_label VARCHAR(64) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    input_csv VARCHAR(512),
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_count INTEGER NOT NULL,
    income NUMERIC(14,2) NOT NULL,
    spend NUMERIC(14,2) NOT NULL
);

CREATE TABLE report_kpis (
    report_year INTEGER PRIMARY KEY REFERENCES reports (report_year) ON DELETE CASCADE,
    income NUMERIC(14,2) NOT NULL,
    spend NUMERIC(14,2) NOT NULL,
    discretionary NUMERIC(14,2) NOT NULL,
    operating_surplus NUMERIC(14,2) NOT NULL,
    savings_rate NUMERIC(10,4) NOT NULL,
    excluded_gross NUMERIC(14,2) NOT NULL,
    excluded_outgoing NUMERIC(14,2) NOT NULL,
    excluded_incoming NUMERIC(14,2) NOT NULL,
    excluded_net NUMERIC(14,2) NOT NULL,
    real_savings_outgoing NUMERIC(14,2) NOT NULL,
    unassigned_surplus NUMERIC(14,2) NOT NULL,
    transactions INTEGER NOT NULL,
    corrections INTEGER NOT NULL,
    low_confidence INTEGER NOT NULL,
    to_check INTEGER NOT NULL,
    to_check_amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE report_monthly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    month_label VARCHAR(7) NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    income NUMERIC(14,2) NOT NULL,
    spend NUMERIC(14,2) NOT NULL,
    discretionary NUMERIC(14,2) NOT NULL,
    excluded NUMERIC(14,2) NOT NULL,
    savings_investments NUMERIC(14,2) NOT NULL,
    net_flow NUMERIC(14,2) NOT NULL,
    savings_rate NUMERIC(10,4) NOT NULL,
    transactions INTEGER NOT NULL,
    spend_per_day NUMERIC(14,2) NOT NULL,
    UNIQUE (report_year, month_key)
);

CREATE TABLE report_category_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    category VARCHAR(160) NOT NULL,
    budget_group VARCHAR(160) NOT NULL,
    spend NUMERIC(14,2) NOT NULL,
    income NUMERIC(14,2) NOT NULL,
    excluded NUMERIC(14,2) NOT NULL,
    monthly_average NUMERIC(14,2) NOT NULL,
    max_month VARCHAR(7),
    max_amount NUMERIC(14,2) NOT NULL,
    discretionary BOOLEAN NOT NULL,
    transaction_count INTEGER NOT NULL,
    UNIQUE (report_year, category)
);

CREATE TABLE report_hierarchy_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    budget_area VARCHAR(160) NOT NULL,
    budget_group VARCHAR(160) NOT NULL,
    category VARCHAR(160) NOT NULL,
    subcategory VARCHAR(160) NOT NULL,
    spend NUMERIC(14,2) NOT NULL,
    income NUMERIC(14,2) NOT NULL,
    excluded NUMERIC(14,2) NOT NULL,
    monthly_average NUMERIC(14,2) NOT NULL,
    transaction_count INTEGER NOT NULL,
    discretionary BOOLEAN NOT NULL
);

CREATE TABLE report_budget_mix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    bucket VARCHAR(160) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    monthly_average NUMERIC(14,2) NOT NULL,
    income_share NUMERIC(10,4) NOT NULL,
    note TEXT NOT NULL
);

CREATE TABLE report_savings_plan (
    report_year INTEGER PRIMARY KEY REFERENCES reports (report_year) ON DELETE CASCADE,
    current_monthly_spend NUMERIC(14,2) NOT NULL,
    current_monthly_income NUMERIC(14,2) NOT NULL,
    core_monthly_cost NUMERIC(14,2) NOT NULL,
    target_monthly_spend NUMERIC(14,2) NOT NULL,
    aggressive_monthly_spend NUMERIC(14,2) NOT NULL,
    target_investment_transfer NUMERIC(14,2) NOT NULL,
    aggressive_investment_transfer NUMERIC(14,2) NOT NULL,
    monthly_cut_needed NUMERIC(14,2) NOT NULL,
    emergency_fund_min NUMERIC(14,2) NOT NULL,
    emergency_fund_comfort NUMERIC(14,2) NOT NULL
);

CREATE TABLE report_category_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    category VARCHAR(160) NOT NULL,
    bucket VARCHAR(160) NOT NULL,
    current_monthly NUMERIC(14,2) NOT NULL,
    limit_amount NUMERIC(14,2) NOT NULL,
    potential_monthly NUMERIC(14,2) NOT NULL,
    potential_yearly NUMERIC(14,2) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    action TEXT NOT NULL
);

CREATE TABLE report_month_control (
    report_year INTEGER PRIMARY KEY REFERENCES reports (report_year) ON DELETE CASCADE,
    month_label VARCHAR(7) NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    elapsed_days INTEGER NOT NULL,
    remaining_days INTEGER NOT NULL,
    days_in_month INTEGER NOT NULL,
    income_to_date NUMERIC(14,2) NOT NULL,
    spend_to_date NUMERIC(14,2) NOT NULL,
    projected_spend NUMERIC(14,2) NOT NULL,
    target_spend NUMERIC(14,2) NOT NULL,
    remaining_budget NUMERIC(14,2) NOT NULL,
    daily_allowed NUMERIC(14,2) NOT NULL,
    projected_delta NUMERIC(14,2) NOT NULL
);

CREATE TABLE report_month_category_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    category VARCHAR(160) NOT NULL,
    bucket VARCHAR(160) NOT NULL,
    current_monthly NUMERIC(14,2) NOT NULL,
    limit_amount NUMERIC(14,2) NOT NULL,
    potential_monthly NUMERIC(14,2) NOT NULL,
    potential_yearly NUMERIC(14,2) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    action TEXT NOT NULL,
    current_month_spend NUMERIC(14,2) NOT NULL,
    current_month_projection NUMERIC(14,2) NOT NULL,
    remaining_this_month NUMERIC(14,2) NOT NULL,
    projected_delta NUMERIC(14,2) NOT NULL,
    usage NUMERIC(10,4) NOT NULL
);

CREATE TABLE report_month_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    alert_type VARCHAR(160) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE report_sinking_funds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(160) NOT NULL,
    monthly_set_aside NUMERIC(14,2) NOT NULL,
    yearly_need NUMERIC(14,2) NOT NULL,
    note TEXT NOT NULL
);

CREATE TABLE report_fixedness_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    fixedness_type VARCHAR(80) NOT NULL,
    spend NUMERIC(14,2) NOT NULL,
    excluded_outgoing NUMERIC(14,2) NOT NULL,
    monthly_average NUMERIC(14,2) NOT NULL,
    transaction_count INTEGER NOT NULL
);

CREATE TABLE report_merchant_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    merchant VARCHAR(256) NOT NULL,
    category VARCHAR(160) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    transaction_count INTEGER NOT NULL,
    average_amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE report_recurring_merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    merchant VARCHAR(256) NOT NULL,
    category VARCHAR(160) NOT NULL,
    bucket VARCHAR(160) NOT NULL,
    total_amount NUMERIC(14,2) NOT NULL,
    months INTEGER NOT NULL,
    transaction_count INTEGER NOT NULL,
    monthly_average NUMERIC(14,2) NOT NULL,
    avg_day INTEGER NOT NULL,
    last_date DATE
);

CREATE TABLE report_large_oneoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    posted_date DATE NOT NULL,
    merchant VARCHAR(256) NOT NULL,
    category VARCHAR(160) NOT NULL,
    bucket VARCHAR(160) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    confidence VARCHAR(32) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE budget_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER NOT NULL REFERENCES reports (report_year) ON DELETE CASCADE,
    lp INTEGER NOT NULL,
    posted_date DATE NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    merchant VARCHAR(256),
    description TEXT,
    account VARCHAR(128),
    bank_category VARCHAR(160),
    corrected_category VARCHAR(160),
    budget_area VARCHAR(160),
    budget_group VARCHAR(160),
    subcategory VARCHAR(160),
    budget_bucket VARCHAR(160),
    fixedness VARCHAR(80),
    transaction_type VARCHAR(80),
    amount NUMERIC(14,2) NOT NULL,
    income NUMERIC(14,2) NOT NULL,
    analysis_spend NUMERIC(14,2) NOT NULL,
    discretionary NUMERIC(14,2) NOT NULL,
    excluded NUMERIC(14,2) NOT NULL,
    excluded_outgoing NUMERIC(14,2) NOT NULL,
    excluded_incoming NUMERIC(14,2) NOT NULL,
    excluded_net NUMERIC(14,2) NOT NULL,
    confidence VARCHAR(32),
    notes TEXT,
    matched_rule TEXT,
    UNIQUE (report_year, lp)
);

CREATE TABLE import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_year INTEGER,
    input_csv VARCHAR(512),
    status VARCHAR(32) NOT NULL,
    message TEXT,
    duplicates_removed INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_reports_imported_at ON reports (imported_at DESC);
CREATE INDEX idx_import_runs_created_at ON import_runs (created_at DESC);
CREATE INDEX idx_import_runs_report_year_created_at ON import_runs (report_year, created_at DESC);
CREATE INDEX idx_monthly_report_month ON report_monthly_summaries (report_year, month_key);
CREATE INDEX idx_categories_report_spend ON report_category_summaries (report_year, spend DESC);
CREATE INDEX idx_hierarchy_report_area ON report_hierarchy_summaries (report_year, budget_area, budget_group, category);
CREATE INDEX idx_budget_transactions_year_month ON budget_transactions (report_year, month_key);
CREATE INDEX idx_budget_transactions_year_posted_date ON budget_transactions (report_year, posted_date);
CREATE INDEX idx_budget_transactions_year_category ON budget_transactions (report_year, corrected_category);
CREATE INDEX idx_budget_transactions_year_subcategory ON budget_transactions (report_year, corrected_category, subcategory);
CREATE INDEX idx_budget_transactions_year_bucket ON budget_transactions (report_year, budget_bucket);
CREATE INDEX idx_budget_transactions_year_area ON budget_transactions (report_year, budget_area);
CREATE INDEX idx_budget_transactions_year_group ON budget_transactions (report_year, budget_group);
CREATE INDEX idx_budget_transactions_year_merchant ON budget_transactions (report_year, merchant);
CREATE INDEX idx_budget_transactions_year_analysis_spend ON budget_transactions (report_year, analysis_spend DESC);
