CREATE TABLE budget_settings_profiles (
    settings_key VARCHAR(64) PRIMARY KEY,
    target_monthly_spend NUMERIC(14,2) NOT NULL,
    aggressive_monthly_spend NUMERIC(14,2) NOT NULL,
    emergency_fund_min_months INTEGER NOT NULL,
    emergency_fund_comfort_months INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE budget_category_limit_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings_key VARCHAR(64) NOT NULL REFERENCES budget_settings_profiles (settings_key) ON DELETE CASCADE,
    category VARCHAR(160) NOT NULL,
    limit_amount NUMERIC(14,2) NOT NULL,
    action TEXT NOT NULL,
    UNIQUE (settings_key, category)
);

CREATE INDEX idx_budget_category_limit_settings_key ON budget_category_limit_settings (settings_key, category);
