package com.budget.domain.transaction;

import java.math.BigDecimal;
import java.time.LocalDate;

public record NormalizedTransaction(
        int lp,
        LocalDate date,
        String month,
        String merchant,
        String description,
        String account,
        String bankCategory,
        String categoryId,
        String correctedCategory,
        String subcategoryId,
        String budgetArea,
        String group,
        String subcategory,
        String flowType,
        String budgetGroupId,
        String budgetGroup,
        String reviewStatus,
        String reviewReason,
        String budgetBucket,
        String fixedness,
        String type,
        BigDecimal amount,
        BigDecimal income,
        BigDecimal analysisSpend,
        BigDecimal discretionary,
        BigDecimal excluded,
        BigDecimal excludedOutgoing,
        BigDecimal excludedIncoming,
        BigDecimal excludedNet,
        String confidence,
        String notes,
        String matchedRule
) {
    public NormalizedTransaction(
            int lp,
            LocalDate date,
            String month,
            String merchant,
            String description,
            String account,
            String bankCategory,
            String correctedCategory,
            String budgetArea,
            String group,
            String subcategory,
            String budgetBucket,
            String fixedness,
            String type,
            BigDecimal amount,
            BigDecimal income,
            BigDecimal analysisSpend,
            BigDecimal discretionary,
            BigDecimal excluded,
            BigDecimal excludedOutgoing,
            BigDecimal excludedIncoming,
            BigDecimal excludedNet,
            String confidence,
            String notes,
            String matchedRule
    ) {
        this(
                lp,
                date,
                month,
                merchant,
                description,
                account,
                bankCategory,
                "",
                correctedCategory,
                "",
                budgetArea,
                group,
                subcategory,
                "",
                "",
                "",
                "ok",
                "",
                budgetBucket,
                fixedness,
                type,
                amount,
                income,
                analysisSpend,
                discretionary,
                excluded,
                excludedOutgoing,
                excludedIncoming,
                excludedNet,
                confidence,
                notes,
                matchedRule
        );
    }
}
