package com.budget.application.reporting;

import java.math.BigDecimal;
import java.time.LocalDate;

public record TransactionRecord(
        long id,
        int lp,
        LocalDate postedDate,
        String month,
        String merchant,
        String description,
        String account,
        String bankCategory,
        String categoryId,
        String correctedCategory,
        String subcategoryId,
        String area,
        String group,
        String subcategory,
        String flowType,
        String budgetGroupId,
        String budgetGroup,
        String reviewStatus,
        String reviewReason,
        String bucket,
        String fixedness,
        String type,
        BigDecimal amount,
        BigDecimal income,
        BigDecimal spend,
        BigDecimal discretionary,
        BigDecimal excluded,
        BigDecimal excludedOutgoing,
        BigDecimal excludedIncoming,
        BigDecimal excludedNet,
        String confidence,
        String notes,
        String matchedRule
) {
    public TransactionRecord(
            long id,
            int lp,
            LocalDate postedDate,
            String month,
            String merchant,
            String description,
            String account,
            String bankCategory,
            String correctedCategory,
            String area,
            String group,
            String subcategory,
            String bucket,
            String fixedness,
            String type,
            BigDecimal amount,
            BigDecimal income,
            BigDecimal spend,
            BigDecimal discretionary,
            BigDecimal excluded,
            BigDecimal excludedOutgoing,
            BigDecimal excludedIncoming,
            BigDecimal excludedNet,
            String confidence,
            String notes,
            String matchedRule
    ) {
        this(
                id,
                lp,
                postedDate,
                month,
                merchant,
                description,
                account,
                bankCategory,
                "",
                correctedCategory,
                "",
                area,
                group,
                subcategory,
                "",
                "",
                "",
                "ok",
                "",
                bucket,
                fixedness,
                type,
                amount,
                income,
                spend,
                discretionary,
                excluded,
                excludedOutgoing,
                excludedIncoming,
                excludedNet,
                confidence,
                notes,
                matchedRule
        );
    }
}
